name: Deploy Node App with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/bicyclebackend
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd ~/bicyclebackend
          npm install

      - name: Restart PM2
        run: |
          pm2 restart bicycleapp || pm2 start index.js --name bicycleapp
          pm2 save
